[producers.sinetest]
type = "sine"
enabled = true
sample_rate = 48000
channels = 2

[processors.pass]
type = "passthrough"

[flows.simple]
enabled = true
inputs = ["sinetest"]
processors = ["pass"]
outputs = ["wavout"]

[consumers.wavout]
type = "file"
enabled = true
path = "out.wav"
