node_name = "airlift-node"

[api]
enabled = true
bind = "127.0.0.1:3008"

[monitoring]
http_port = 3008

[ringbuffers.main]
slots = 6000
prealloc_samples = 9600

[inputs.sine]
type = "producer"
enabled = true
buffer = "main"

[outputs.file]
type = "consumer"
enabled = true
buffer = "main"
input = "sine"
codec_id = "passthrough"

[codecs.passthrough]
type = "processor"
sample_rate = 48000
channels = 2
