node_name = "test-node"

[producers.test]
type = "file"
enabled = true
path = "background.wav"
loop_audio = true
channels = 2
sample_rate = 48000

[processors.pass]
type = "passthrough"
enabled = true

[consumers.record]
type = "file"
enabled = true
path = "simple_test.wav"

[flows.simple]
enabled = true
inputs = ["test"]
processors = ["pass"]
outputs = ["record"]
